blank_issues_enabled: false

contact_links:
  - name: Issues with formatting results (c_formatter_42 issue)
    url: https://github.com/dawnbeen/c_formatter_42/issues/new/choose
    about: Please open issues in dawnbeen/c_formatter_42.
